kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitbucket-pv-claim
  labels:
    app: bitbucket
spec:
  storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
