apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-bitbucket-pvc-deployment
  namespace: mcm-bitbucket-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: bitbucket
spec:

